---
# defaults file for virtualenv_migrate
venv_migrate_default_venv_paths:
  - "/var/lib/awx/venv/ansible/"
venv_migrate_default_ee_url: "registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest"
venv_migrate_show_diff_with_default: False
venv_migrate_registry_username: "{{ registry_username }}"
venv_migrate_registry_password: "{{ registry_password }}"

